### PR TITLE
Retry on SDIO Write errors.

### PR DESCRIPTION
**Pull request by nsloss**
This fixes issues I experinced on a BlueSCSI-v2 with wifi PowerBook Edition.

Retrying the writing of the block resulted in no further write errors reported to NetBSD-current 2024-11-20.

The patch in issue #210 was garbled by the web form.  This is the patch in it's complete form.

Best regards,

Nat

### CODE REVIEW

**Comment by erichelgeson** [comment]
Friendly ping - hopefully you saw my comment on your issue - if you could test that scenario.

**Comment by nsloss** [comment]
I can confirm so fat 2024-11-17 is working just fine.

There are no errors reported in NetBSD and so far.  I've read/written about 500MB.

Many thanks,

I'll keep testing for a day or two, but otherwise this issue can be closed.

Best regards,

Nat

**Comment by nsloss** [comment]
closing this issue and pull request as the latest version 2024-11-17 is working great.

Many thanks to all that looked at this.

Best regards,

Nat

**Comment by erichelgeson** [comment]
Glad to hear! Thanks for digging in anyways - if you ever have any other issue please let us know.

If you had some time to do a little write up on how you're using BlueSCSI in NetBSD on your powebook I'd be very interested in reading that!

**Pull request closed without merging**
