### PR TITLE
Add SCSI ethernet support, emulating a Dayna SCSI/Link

### PR DESCRIPTION
**Pull request by jcs**

### CODE REVIEW

**Comment by erichelgeson** [comment]
Binaries are built in the GitHub Actions here: https://github.com/BlueSCSI/BlueSCSI-v2/actions/runs/5771395373

Documentation can be found here: https://github.com/BlueSCSI/BlueSCSI-v2/wiki/WiFi-DaynaPORT

**Comment by jcs** [comment]
Added more vendor commands to get wifi status.

I also added a check that we're running on the Pico W before doing any network initialization.  If running on a non-W Pico, it just logs a message and ignores the NE# file:

> 21:03:43:403 -> -- Ignoring /NE4.txt, networking is not supported on this hardware

**Comment by jcs** [comment]
Fixed booting on the Mac Plus with a workaround, added vendor command to join a new network, changed Dayna driver delay back to 80us which seems to work on the Plus.

Fetch is plugging along downloading a file at 14 kbytes/sec on my Plus with these changes.

**Comment by jcs** [comment]
This change uses `pico_get_unique_board_id` to get the Pico's ID when constructing a default MAC address (if not specified in `bluescsi.ini`) to avoid having more than one BlueSCSI on a network using the default `00:80:19:c0:ff:ee`.  From my testing on two Pico Ws, this unique board id persists across firmware reflashes so it should be stable and unique.

From the `pico_get_unique_board_id` docs:

> However, RP2040 boots from serial NOR flash devices which have a 64-bit unique ID as a standard feature, and there is a 1:1 association between RP2040 and flash, so this is suitable for use as a unique identifier for an RP2040-based board.

**Comment by jcs** [comment]
"Wi-Fi"

**Comment by jcs** [comment]
These changes do the multicast magic to enable EtherTalk and reorganizes the custom Wi-Fi SCSI commands that the Wi-Fi DA uses.  I've given up trying to use custom opcodes in the custom vendor `C0-FF` range because the SCSI Manager in Mac OS doesn't like it, and am just using one opcode with a sub-command in the CDB for each Wi-Fi command.

**Comment by androda** [comment]
Looks like configuring the INI file but then failing to specify a network device causes a hang and failure to boot.

**Comment by jcs** [comment]
You mean just setting the SSID and password but no `NE#.txt` file?  I'm not seeing how they would have any impact on anything, they are just copied into the global config object during INI parsing and would not be used by anything.

**Comment by androda** [comment]
Correct, that combination caused my beige g3 to not boot.  After adding an NE# file the issue was resolved.

**Comment by tazounet** [comment]
Thanks for the WiFi support, it works well on my PB100 :)
But it seems to break the ROM disk support (if I switch back to the "official" version, the ROM disk is back).

**Comment by erichelgeson** [comment]
Sorry for the long delay @tazounet - I can reproduce your issue - we'll look into it. Thanks for the report.

**Comment by fdanapfel** [comment]
Thanks for the WiFi support! It also works well on the Atari TT :)

**Review by erichelgeson — APPROVED** [review]
🛜

**Pull request merged**
